name=VT100
version=1.0.0
author=Sarvagya Jain
maintainer=Sarvagya Jain
sentence=VT100 terminal control library for Arduino
paragraph=Provides cursor control, text positioning, and UI features using ANSI escape sequences.
category=Display
url=https://github.com/Sarvags/VT100-Arduino
architectures=*
